# Generated by Django 3.0.2 on 2020-01-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField(help_text='Enter in years')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Entry')),
                ('illness', models.CharField(max_length=25, verbose_name='Major Illness Found')),
                ('comment', models.TextField(verbose_name="Doctor's Comment")),
                ('medicine', models.TextField()),
                ('duration', models.DateTimeField(default=None)),
                ('completion', models.BooleanField(help_text='Whether treatment was completed or still in proress')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DoctorProfile')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PatientProfile')),
            ],
        ),
    ]
