# Generated by Django 3.0.2 on 2020-01-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecords',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='medicalrecords',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
