# Generated by Django 3.0.2 on 2020-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200117_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='completion',
            field=models.BooleanField(default=False, help_text='Whether treatment was completed or still in proress'),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
