# Generated by Django 3.0.2 on 2020-01-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200118_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='completion',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
