# Generated by Django 3.0.2 on 2020-01-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200126_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecords',
            name='completion',
        ),
    ]
